name: test-ansible

on:
  workflow_dispatch:

jobs:
  ping-internal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test internal inventory connectivity
        working-directory: ansible
        run: |
          ping lang-docker-01.internal -c 4
