name: test-ansible

on:
  workflow_dispatch:

jobs:
  ping-internal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          set -e
          if command -v apt-get >/dev/null 2>&1; then
            apt-get update
            apt-get install -y iputils-ping ansible openssh-client rsync
          elif command -v apk >/dev/null 2>&1; then
            apk add --no-cache iputils ansible openssh-client rsync
          else
            echo "No supported package manager found (apt-get/apk)."
            exit 1
          fi

      - name: Ping docker host
        run: |
          ping -c 2 lang-docker-01.internal
